#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR=$1

source "$CADMIUMROOT/config"

debootstrap --components=main,restricted,universe,multiverse --arch="$ARCH_DEB" "$SUITE" "$DESTDIR" http://ports.ubuntu.com/ubuntu-ports/

chroot "$DESTDIR" apt update
